language: ruby
cache: bundler
dist: bionic
env:
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=6.0.0"
  - "RAILS_VERSION=6.1.0"
rvm:
  - 2.7.2
  - 3.0.2
before_install:
  - gem update bundler
jobs:
  exclude:
  - rvm: 3.0.2
    env: "RAILS_VERSION=5.2.0"
